name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "18.18.x"
        cache: npm
    - name: Install packages
      run: make install
      shell: bash
