[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
chapel = "https://data-seed-prebsc-1-s1.binance.org:8545"
mumbai = "https://rpc-mumbai.maticvigil.com/"
fuji = "https://avalanche-fuji.infura.io/v3/${INFURA_KEY}"
bsc = "https://bsc-dataseed.binance.org/"
ethereum = "https://mainnet.infura.io/v3/${INFURA_KEY}"
polygon = "https://matic-mainnet.chainstacklabs.com"
avalanche = "https://api.avax.network/ext/bc/C/rpc"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }
bsc = { key = "${BSCSCAN_KEY}" }
chapel = { key = "${BSCSCAN_KEY}" }
mumbai = { key = "${POLYGONSCAN_KEY}" }
polygon = { key = "${POLYGONSCAN_KEY}" }
fuji = { key = "${AVALANCHE_KEY}" }
avalanche = { key = "${AVALANCHE_KEY}" }
