[profile.default]
src = "contracts"
out = "out"
test = "tests"
script = "scripts"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
    "@contracts/=./contracts/",
    "@tests/=./tests/",
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable",
    "@solarity/=lib/solidity-lib",
    "@forge-std/=lib/forge-std/src",
    "@/=./"
]

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
chapel = "https://data-seed-prebsc-1-s1.binance.org:8545"
bsc = "https://bsc-dataseed.binance.org/"
ethereum = "https://mainnet.infura.io/v3/${INFURA_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }
bsc = { key = "${BSCSCAN_KEY}" }
chapel = { key = "${BSCSCAN_KEY}", url = "https://api-testnet.bscscan.com/" }
