name: "checks"

env:
  FOUNDRY_PROFILE: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: make test
